# -*- coding: utf-8 -*-
"""AI Machine Learning Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1woQ9vzbBnkrh2eUQyULSR8mp5GcK_Kia
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skewnorm
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
import sklearn.metrics as metrics
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import KFold, cross_val_score
from sklearn.metrics import make_scorer, r2_score

df = pd.read_csv('/content/drive/MyDrive/CMP6202/datasets/used_cars.csv')

"""# Exploratory Data Analysis"""

df.head()

df['accident'].value_counts()

df['transmission'].value_counts()

df['engine'].value_counts()

df['fuel_type'].value_counts()

# Count and display unique brands. Testing to see how i will pre-process the data.
unique_brands = df['brand'].nunique()
print("Number of unique brands:", unique_brands)

# Show a sample of unique brands to see if one hot encoding will be suitable
print("Unique brands:", df['brand'].unique())
#[:20]

# Checking the unique colors in the dataset
unique_colors = df['int_col'].unique()
print("Unique colors:", unique_colors)
print("Number of unique colors:", len(unique_colors))

# Checking the unique colors in the dataset
unique_colors = df['ext_col'].unique()
print("Unique colors:", unique_colors)
print("Number of unique colors:", len(unique_colors))

unique_fueltype = df['fuel_type'].nunique()
print("Number of unique fuel types:", unique_fueltype)

print("Unique brands:", df['fuel_type'].unique()[:20])

df.isna().sum()

"""I had some issues with visualisation techniques. The graphs are sometimes unreadable and i am not sure why this happens. The correct outputs have been included in my report."""

sns.scatterplot(data=df, x='milage', y='price')

sns.scatterplot(data=df, x='model_year', y='price')

sns.barplot(data=df, x='accident', y='price')

sns.barplot(data=df, x='fuel_type', y='price')

df['clean_title'].value_counts()
#drop this column entirely. not useful data?

sns.barplot(data=df, x='transmission', y='price')
#too many different transmissions make the plot unreadable. But some are definitely more expensive than others.

#df.isna().sum()

"""# Data PreProcessing"""

df['price'] = df['price'].str.replace('$', '').str.replace(',', '').astype(float)
df['price'].head()

df['milage'] = df['milage'].str.replace('mi', '').str.replace(',', '').str.replace(' ', '').astype(float)
df['milage'].head()

df.drop(columns=['clean_title'], inplace=True)

df.head()

#le = LabelEncoder()
#print(df['accident'].unique())
#df['accident'] = le.fit_transform(df['accident'])
#df['accident'].head(7)

#originally tried label encoding but it was labelling it in a less intuitive way. Cars that had accidents reported were being labelled as 0 and cars with no accidents were being labelled as 1. This could make it confusing and difficult to read.

df['accident'].value_counts()

df['accident'].isna().sum()

df['accident'] = df['accident'].replace('None reported', 0)
df['accident'] = df['accident'].replace('At least 1 accident or damage reported', 1)

df['accident'] = df['accident'].fillna(0) #imputing most common value
df['accident'] = df['accident'].astype(int)

df['accident'].value_counts()

df['accident'].isna().sum()

df = df.drop(columns=['ext_col', 'int_col', 'model', 'engine'])

df.head()

most_common_transmissions = df['transmission'].value_counts().head(5).index

def group_transmissions(tran):
  if tran in most_common_transmissions:
    return tran
  else:
    return 'Other'

df['transmission'] = df['transmission'].apply(group_transmissions)

#label encoding giving incorrect results. I will use manual encoding instead.
#le = LabelEncoder()
#df['transmission'] = le.fit_transform(df['transmission'])
#df['transmission'].head(7)

df['transmission'].value_counts()

df['transmission'] = df['transmission'].replace('A/T', 0)
df['transmission'] = df['transmission'].replace('8-Speed A/T', 1)
df['transmission'] = df['transmission'].replace('Transmission w/Dual Shift Mode', 2)
df['transmission'] = df['transmission'].replace('6-Speed A/T', 3)
df['transmission'] = df['transmission'].replace('6-Speed M/T', 4)
df['transmission'] = df['transmission'].replace('Other', 5)

df['transmission'].value_counts()
#successfully encoded!

df['fuel_type'].value_counts()

most_common_fueltypes = df['fuel_type'].value_counts().head(4).index

def group_fueltypes(type):
  if type in most_common_fueltypes:
    return type
  else:
    return 'Other'

df['fuel_type'] = df['fuel_type'].apply(group_fueltypes)

df['fuel_type'].value_counts()

df['fuel_type'] = df['fuel_type'].replace('Gasoline', 0)
df['fuel_type'] = df['fuel_type'].replace('Hybrid', 1)
df['fuel_type'] = df['fuel_type'].replace('E85 Flex Fuel', 2)
df['fuel_type'] = df['fuel_type'].replace('Diesel', 3)
df['fuel_type'] = df['fuel_type'].replace('Other', 4)

df['fuel_type'].head(20)

df.head()

Exotic_brands = ('Aston', 'Bentley', 'Ferrari', 'Lamborhini', 'Rolls-Royce', 'Bugatti', 'McLaren')
Luxury_brands = ('Audi', 'BMW', 'Lexus', 'Mercedes-Benz', 'Porsche', 'Tesla','Jaguar', 'Land','Maserati','Genesis')
MidRange_brands = ('Acura', 'Lincoln', 'Volvo','MINI', 'Cadillac', 'Subaru','GMC','RAM','Volkswagen','Alfa')
Economy_brands = ('Ford','Hyundai','Toyota','Honda','Nissan','Chevrolet','Kia','Jeep','Dodge','Mazda','Mitsubishi','Chrysler','Buick','Saturn','Pontiac','FIAT','Suzuki')
Other_brands = ('Lucid','Hummer','Rivian','Scion','Polestar','Lotus','Mercury','Plymouth','Saab','Maybach','smart','Karma')

def group_brands(brand):
  if brand in Exotic_brands:
    return '1' #1 = exotic
  elif brand in Luxury_brands:
    return '2' #2 = luxury
  elif brand in MidRange_brands:
    return '3' #3 = mid range
  elif brand in Economy_brands:
    return '4' #4= economy
  else:
    return '5' #5 = other brands. these brands are not very common or less known brands.


df['brand'] = df['brand'].apply(group_brands)

#irrelevant cell - this was checking the label encoding which i did initially.
#df['accident'].value_counts() #empty values that were previously present have been turned into 2. Need to impute data most likely. '1' is none reported. '0' is accident reported

df['brand'] = df['brand'].astype(int)

df['brand'].value_counts()

df.info()

df.head()

"""# Model Development"""

X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

rf_model = RandomForestRegressor(n_estimators=300, random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

y_train_pred = rf_model.predict(X_train)

#seen data
mse = mean_squared_error(y_train, y_train_pred)
r2 = r2_score(y_train, y_train_pred)
print("Training MSE:", mse)
print("Trainig R squared:", r2)

plt.figure(figsize=(8, 6))
residuals = y_train - rf_model.predict(X_train)
sns.histplot(residuals, kde=True, bins=30, color='purple')
plt.title('Histogram of Residuals (Training Data)')
plt.xlabel('Residuals')
plt.ylabel('Frequency')
plt.show()

#test data
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print("MSE:", mse)
print("R squared:", r2)

plt.figure(figsize=(8, 6))
plt.scatter(y_train, rf_model.predict(X_train), alpha=0.5)
plt.plot([min(y_train), max(y_train)], [min(y_train), max(y_train)], color='red', linestyle='--')
plt.title('Actual vs Predicted (Training Data)')
plt.xlabel('Actual Values')
plt.ylabel('Predicted Values')
plt.show()

feature_importances = rf_model.feature_importances_

features = X.columns

# Dataframe to hold feature names
importance_df = pd.DataFrame({
    'Feature': features,
    'Importance': feature_importances
})

# Sort DataFrame based on importance
importance_df = importance_df.sort_values(by='Importance', ascending=False)

# Plotting
plt.figure(figsize=(10, 6))
plt.barh(importance_df['Feature'], importance_df['Importance'])
plt.xlabel('Feature Importance')
plt.ylabel('Features')
plt.title('Random forest feature importance')
plt.show()

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_train_pred_linearreg = lr_model.predict(X_train)

#seen data
mse_linearreg = mean_squared_error(y_train, y_train_pred_linearreg)
r2_linearreg = r2_score(y_train, y_train_pred_linearreg)
print("MSE:", mse_linearreg)
print("R squared:", r2_linearreg)

y_pred_linearreg = lr_model.predict(X_test)

#test data
mse_linearreg = mean_squared_error(y_test, y_pred_linearreg)
r2_linearreg = r2_score(y_test, y_pred_linearreg)
print("MSE:", mse_linearreg)
print("R squared:", r2_linearreg)

# Random forest statistics
rf_train_r2 = 0.9366080768387286
rf_test_r2 = 0.13964252937259924
rf_test_mse = 17585337646.853184

# Linear regression statistics

lr_train_r2 = 0.2284427507475456
lr_test_r2 = 0.03548714301955447
lr_test_mse = 19714229066.161797

# Bar chart for R² scores
models = ['Random Forest', 'Linear Regression']
train_r2 = [rf_train_r2, lr_train_r2]
test_r2 = [rf_test_r2, lr_test_r2]

x = np.arange(len(models))

plt.figure(figsize=(10, 6))
plt.bar(x - 0.1, train_r2, width=0.2, label='Training R²', color='skyblue')
plt.bar(x + 0.1, test_r2, width=0.2, label='Testing R²', color='purple')

plt.xticks(x, models)
plt.ylabel('R² Score')
plt.title('R² Score Comparison: Random Forest vs Linear Regression')
plt.legend()
plt.show()

"""#Grid Search"""

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 300, 500],
    'max_depth': [10, 15, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 5, 10]
}

# Instantiate the GridSearchCV
grid_search = GridSearchCV(estimator=RandomForestRegressor(random_state=42),
                           param_grid=param_grid,
                           cv=5,  # 5-Fold Cross-Validation
                           scoring='r2',
                           n_jobs=-1)

# Fit the grid search model
grid_search.fit(X_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best R2 Score:", grid_search.best_score_)

"""#Model Improvement and tuning

Random forest
"""

Improved_rf_model = RandomForestRegressor(n_estimators=500, max_depth=10, min_samples_split=2, min_samples_leaf=5, random_state=42)

kf = KFold(n_splits=5, shuffle=True, random_state=42)

cv_results = cross_val_score(Improved_rf_model, X_train, y_train, cv=kf, scoring='r2')

print("Cross-Validation R2 Scores:", cv_results)
print("Mean R2 Score:", np.mean(cv_results))

"""Linear regression tuning"""

improved_linearreg_model = LinearRegression(positive = True)

kf = KFold(n_splits=10, shuffle=True, random_state=42)

linearreg_cv_results = cross_val_score(improved_linearreg_model, X_train, y_train, cv=kf, scoring='r2')

print("Cross-Validation R2 Scores:", linearreg_cv_results)
print("Mean R2 Score:", np.mean(linearreg_cv_results))

improved_linearregression_score = 0.13
improved_random_forest_Score = 0.57

models = ['Improved Linear Regression', 'Improved Random Forest']
scores = [improved_linearregression_score, improved_random_forest_Score]

plt.figure(figsize=(10, 6))
plt.bar(models, scores)
plt.ylabel('R² Score')
plt.title('R² Score Comparison: Improved Linear Regression vs Improved Random Forest')
plt.show()

"""#Final Model Evaluation"""

#removing potential outliers. The category 5 is labelled as 'Other' which could contain data that confuses the model.
df_filtered = df[df['brand'] != 5]

# Model Development -
X_filtered = df_filtered.drop('price', axis=1)
y_filtered = df_filtered['price']

X_train, X_test, y_train, y_test = train_test_split(X_filtered, y_filtered, test_size=0.2, random_state=42)

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Improved_rf_model = RandomForestRegressor(n_estimators=500, max_depth=10, min_samples_split=10, min_samples_leaf=10, random_state=42)
Improved_rf_model.fit(X_train, y_train)

y_pred = Improved_rf_model.predict(X_test)
y_train_pred = Improved_rf_model.predict(X_train)

# Model Evaluation
mse_train = mean_squared_error(y_train, y_train_pred)
r2_train = r2_score(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_pred)
r2_test = r2_score(y_test, y_pred)

print("Training MSE:", mse_train)
print("Training R²:", r2_train)
print("Test MSE:", mse_test)
print("Test R²:", r2_test)

# Old Random forest statistics
rf_train_r2 = 0.9366080768387286
rf_test_r2 = 0.13964252937259924
rf_test_mse = 17585337646.853184

# Final Model RF Statistics

FRF_train_r2 = 0.321409535387161
FRF_test_r2 = 0.3532894533396125
FRF_test_mse = 4685277028.678787

# Bar chart for R² scores
models = ['Initial Random Forest Model', 'Final Random Forest Model']
train_r2 = [rf_train_r2, FRF_train_r2]
test_r2 = [rf_test_r2, FRF_test_r2]

x = np.arange(len(models))

plt.figure(figsize=(10, 6))
plt.bar(x - 0.1, train_r2, width=0.2, label='Training R²', color='skyblue')
plt.bar(x + 0.1, test_r2, width=0.2, label='Testing R²', color='purple')

plt.xticks(x, models)
plt.ylabel('R² Score')
plt.title('R² Score Comparison: Initial Random Forest vs Final Random Forest')
plt.legend()
plt.show()